(require "asdf")

(let* ((root (make-pathname :name nil :type nil :defaults (or *load-truename*
                                                              *compile-file-truename*)))
       (asd (merge-pathnames #P"bootwright.asd" root)))
  (asdf:load-asd asd)
  (asdf:operate 'asdf:load-source-op :bootwright)
  (let ((builder (symbol-function (find-symbol "BUILD-OS-SOURCE-FILE" "BOOTWRIGHT"))))
    (dolist (spec '(("examples/basics/demo-real.bwo"         "out/basics/bootwright-demo.img")
                    ("examples/basics/demo-assets.bwo"       "out/basics/bootwright-assets.img")
                    ("examples/protected/demo-protected.bwo" "out/protected/bootwright-protected.img")
                    ("examples/devices/demo-timer.bwo"       "out/devices/bootwright-timer.img")
                    ("examples/devices/demo-probe.bwo"       "out/devices/bootwright-probe.img")
                    ("examples/devices/demo-keyboard.bwo"    "out/devices/bootwright-keyboard.img")
                    ("examples/devices/demo-ata.bwo"         "out/devices/bootwright-ata.img")
                    ("examples/devices/demo-memmap.bwo"      "out/devices/bootwright-memmap.img")
                    ("examples/devices/demo-physalloc.bwo"   "out/devices/bootwright-physalloc.img")
                    ("examples/cpu/demo-cpuinfo.bwo"         "out/cpu/bootwright-cpuinfo.img")
                    ("examples/cpu/demo-bench.bwo"           "out/cpu/bootwright-bench.img")
                    ("examples/cpu/demo-memops.bwo"          "out/cpu/bootwright-memops.img")
                    ("examples/cpu/demo-sysinstr.bwo"        "out/cpu/bootwright-sysinstr.img")
                    ("examples/exec/demo-context.bwo"        "out/exec/bootwright-context.img")
                    ("examples/exec/demo-syscalls.bwo"       "out/exec/bootwright-syscalls.img")
                    ("examples/exec/demo-userspace.bwo"      "out/exec/bootwright-userspace.img")
                    ("examples/exec/demo-sysenter.bwo"       "out/exec/bootwright-sysenter.img")
                    ("examples/devices/demo-storage.bwo"     "out/devices/bootwright-storage.img")))
      (destructuring-bind (source output) spec
        (let ((pathname (funcall builder
                                 (merge-pathnames source root)
                                 :output (merge-pathnames output root))))
          (format t "Bootwright image written to ~A~%" pathname))))))
